# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import files_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 550)
        MainWindow.setMinimumSize(QtCore.QSize(400, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/calculator.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget {\n"
                                 "    color: #121212;\n"
                                 "    background-color: white;\n"
                                 "    font-family: Bahnschrift Light;\n"
                                 "    font-size: 14pt;\n"
                                 "    font-weight: 500;\n"
                                 "}\n"
                                 "QPushButton {\n"
                                 "    background-color: transparent;\n"
                                 "    border: none;\n"
                                 "}\n"
                                 "QPushButton:hover {\n"
                                 "    background-color: #7FFFD4;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: #3CB371;\n"
                                 "}")
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_temp = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_temp.sizePolicy().hasHeightForWidth())
        self.lbl_temp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.lbl_temp.setFont(font)
        self.lbl_temp.setStyleSheet("color: #666;")
        self.lbl_temp.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lbl_temp.setObjectName("lbl_temp")
        self.verticalLayout.addWidget(self.lbl_temp)
        self.le_entry = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_entry.sizePolicy().hasHeightForWidth())
        self.le_entry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(62)
        self.le_entry.setFont(font)
        self.le_entry.setStyleSheet("font-size: 40pt;\n"
                                    "border: none;")
        self.le_entry.setMaxLength(16)
        self.le_entry.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.le_entry.setReadOnly(True)
        self.le_entry.setObjectName("le_entry")
        self.verticalLayout.addWidget(self.le_entry)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5.sizePolicy().hasHeightForWidth())
        self.btn_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.btn_5.setFont(font)
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 3, 1, 1, 1)
        self.b_multiply = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_multiply.sizePolicy().hasHeightForWidth())
        self.b_multiply.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_multiply.setFont(font)
        self.b_multiply.setStyleSheet("QPushButton {\n"
                                      "    background-color: #4682B4;\n"
                                      "    border: none;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #7FFFD4;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: #3CB371;\n"
                                      "}")
        self.b_multiply.setObjectName("b_multiply")
        self.gridLayout.addWidget(self.b_multiply, 2, 3, 1, 1)
        self.b_divide = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_divide.sizePolicy().hasHeightForWidth())
        self.b_divide.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_divide.setFont(font)
        self.b_divide.setStyleSheet("QPushButton {\n"
                                    "    background-color: #4682B4;\n"
                                    "    border: none;\n"
                                    "}\n"
                                    "QPushButton:hover {\n"
                                    "    background-color: #7FFFD4;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed {\n"
                                    "    background-color: #3CB371;\n"
                                    "}")
        self.b_divide.setObjectName("b_divide")
        self.gridLayout.addWidget(self.b_divide, 1, 3, 1, 1)
        self.b_equal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_equal.sizePolicy().hasHeightForWidth())
        self.b_equal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_equal.setFont(font)
        self.b_equal.setStyleSheet("QPushButton {\n"
                                   "    background-color: #191970;\n"
                                   "    border: none;\n"
                                   "}\n"
                                   "QPushButton:hover {\n"
                                   "    background-color: #7FFFD4;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "    background-color: #3CB371;\n"
                                   "}")
        self.b_equal.setObjectName("b_equal")
        self.gridLayout.addWidget(self.b_equal, 5, 3, 1, 1)
        self.b_ce = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_ce.sizePolicy().hasHeightForWidth())
        self.b_ce.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_ce.setFont(font)
        self.b_ce.setObjectName("b_ce")
        self.gridLayout.addWidget(self.b_ce, 1, 1, 1, 1)
        self.b_c = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_c.sizePolicy().hasHeightForWidth())
        self.b_c.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_c.setFont(font)
        self.b_c.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.b_c.setObjectName("b_c")
        self.gridLayout.addWidget(self.b_c, 1, 0, 1, 1)
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0.sizePolicy().hasHeightForWidth())
        self.btn_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.btn_0.setFont(font)
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 5, 1, 1, 1)
        self.b_point = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_point.sizePolicy().hasHeightForWidth())
        self.b_point.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_point.setFont(font)
        self.b_point.setObjectName("b_point")
        self.gridLayout.addWidget(self.b_point, 5, 2, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1.sizePolicy().hasHeightForWidth())
        self.btn_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.btn_1.setFont(font)
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 4, 0, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2.sizePolicy().hasHeightForWidth())
        self.btn_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.btn_2.setFont(font)
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 4, 1, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4.sizePolicy().hasHeightForWidth())
        self.btn_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.btn_4.setFont(font)
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 3, 0, 1, 1)
        self.b_plus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_plus.sizePolicy().hasHeightForWidth())
        self.b_plus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_plus.setFont(font)
        self.b_plus.setStyleSheet("QPushButton {\n"
                                  "    background-color: #4682B4;\n"
                                  "    border: none;\n"
                                  "}\n"
                                  "QPushButton:hover {\n"
                                  "    background-color: #7FFFD4;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "    background-color: #3CB371;\n"
                                  "}")
        self.b_plus.setObjectName("b_plus")
        self.gridLayout.addWidget(self.b_plus, 4, 3, 1, 1)
        self.b_minus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_minus.sizePolicy().hasHeightForWidth())
        self.b_minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_minus.setFont(font)
        self.b_minus.setStyleSheet("QPushButton {\n"
                                   "    background-color: #4682B4;\n"
                                   "    border: none;\n"
                                   "}\n"
                                   "QPushButton:hover {\n"
                                   "    background-color: #7FFFD4;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "    background-color: #3CB371;\n"
                                   "}")
        self.b_minus.setObjectName("b_minus")
        self.gridLayout.addWidget(self.b_minus, 3, 3, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3.sizePolicy().hasHeightForWidth())
        self.btn_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.btn_3.setFont(font)
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 4, 2, 1, 1)
        self.b_deg = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_deg.sizePolicy().hasHeightForWidth())
        self.b_deg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_deg.setFont(font)
        self.b_deg.setStyleSheet("QPushButton {\n"
                                 "    background-color: #008080;\n"
                                 "    border: none;\n"
                                 "}\n"
                                 "QPushButton:hover {\n"
                                 "    background-color: #7FFFD4;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: #3CB371;\n"
                                 "}")
        self.b_deg.setObjectName("b_deg")
        self.gridLayout.addWidget(self.b_deg, 0, 1, 1, 1)
        self.b_sqrt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_sqrt.sizePolicy().hasHeightForWidth())
        self.b_sqrt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_sqrt.setFont(font)
        self.b_sqrt.setStyleSheet("QPushButton {\n"
                                  "    background-color: #008080;\n"
                                  "    border: none;\n"
                                  "}\n"
                                  "QPushButton:hover {\n"
                                  "    background-color: #7FFFD4;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "    background-color: #3CB371;\n"
                                  "}")
        self.b_sqrt.setObjectName("b_sqrt")
        self.gridLayout.addWidget(self.b_sqrt, 0, 2, 1, 1)
        self.b_deg_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_deg_2.sizePolicy().hasHeightForWidth())
        self.b_deg_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_deg_2.setFont(font)
        self.b_deg_2.setStyleSheet("QPushButton {\n"
                                   "    background-color: #008080;\n"
                                   "    border: none;\n"
                                   "}\n"
                                   "QPushButton:hover {\n"
                                   "    background-color: #7FFFD4;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "    background-color: #3CB371;\n"
                                   "}")
        self.b_deg_2.setObjectName("b_deg_2")
        self.gridLayout.addWidget(self.b_deg_2, 0, 0, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6.sizePolicy().hasHeightForWidth())
        self.btn_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.btn_6.setFont(font)
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 3, 2, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8.sizePolicy().hasHeightForWidth())
        self.btn_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.btn_8.setFont(font)
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 2, 1, 1, 1)
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7.sizePolicy().hasHeightForWidth())
        self.btn_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.btn_7.setFont(font)
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 2, 0, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_9.sizePolicy().hasHeightForWidth())
        self.btn_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.btn_9.setFont(font)
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 2, 2, 1, 1)
        self.b_rt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_rt.sizePolicy().hasHeightForWidth())
        self.b_rt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_rt.setFont(font)
        self.b_rt.setStyleSheet("QPushButton {\n"
                                "    background-color: #008080;\n"
                                "    border: none;\n"
                                "}\n"
                                "QPushButton:hover {\n"
                                "    background-color: #7FFFD4;\n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed {\n"
                                "    background-color: #3CB371;\n"
                                "}")
        self.b_rt.setObjectName("b_rt")
        self.gridLayout.addWidget(self.b_rt, 0, 3, 1, 1)
        self.b_negative = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_negative.sizePolicy().hasHeightForWidth())
        self.b_negative.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_negative.setFont(font)
        self.b_negative.setObjectName("b_negative")
        self.gridLayout.addWidget(self.b_negative, 5, 0, 1, 1)
        self.b_back = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_back.sizePolicy().hasHeightForWidth())
        self.b_back.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.b_back.setFont(font)
        #self.b_back.setText("")
        self.b_back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/backspace.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_back.setIcon(icon1)
        self.b_back.setIconSize(QtCore.QSize(40, 40))
        self.b_back.setObjectName("b_back")
        self.gridLayout.addWidget(self.b_back, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.lbl_temp.setText(_translate("MainWindow", ""))
        self.le_entry.setText(_translate("MainWindow", "0"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_5.setShortcut(_translate("MainWindow", "5"))
        self.b_multiply.setText(_translate("MainWindow", "*"))
        self.b_multiply.setShortcut(_translate("MainWindow", "*"))
        self.b_divide.setText(_translate("MainWindow", "/"))
        self.b_divide.setShortcut(_translate("MainWindow", "/"))
        self.b_equal.setText(_translate("MainWindow", "="))
        #self.b_equal.setShortcut(_translate("MainWindow", "="))
        self.b_equal.setShortcut(_translate("MainWindow", "Enter"))
        self.b_ce.setText(_translate("MainWindow", "СЕ"))
        self.b_ce.setShortcut(_translate("MainWindow", "Del"))
        self.b_c.setText(_translate("MainWindow", "С"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_0.setShortcut(_translate("MainWindow", "0"))
        self.b_point.setText(_translate("MainWindow", "."))
        self.b_point.setShortcut(_translate("MainWindow", "."))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_1.setShortcut(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_2.setShortcut(_translate("MainWindow", "2"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_4.setShortcut(_translate("MainWindow", "4"))
        self.b_plus.setText(_translate("MainWindow", "+"))
        self.b_plus.setShortcut(_translate("MainWindow", "+"))
        self.b_minus.setText(_translate("MainWindow", "-"))
        self.b_minus.setShortcut(_translate("MainWindow", "-"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_3.setShortcut(_translate("MainWindow", "3"))
        self.b_deg.setText(_translate("MainWindow", "x^n"))
        self.b_sqrt.setText(_translate("MainWindow", "sqrt(x)"))
        self.b_deg_2.setText(_translate("MainWindow", "x^2"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_6.setShortcut(_translate("MainWindow", "6"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_8.setShortcut(_translate("MainWindow", "8"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_7.setShortcut(_translate("MainWindow", "7"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_9.setShortcut(_translate("MainWindow", "9"))
        self.b_rt.setText(_translate("MainWindow", "rt(x, n)"))
        self.b_negative.setText(_translate("MainWindow", "+/-"))
        self.b_back.setShortcut(_translate("MainWindow", "Backspace"))




if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
